apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-utside
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://tiltak-refusjon.dev.nav.no
  tokenx:
    enabled: true
  idporten:
    enabled: true
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 1
  env:
    - name: DECORATOR_URL
      value: https://dekoratoren.dev.nav.no
    - name: API_AUDIENCE
      value: "dev-gcp:arbeidsgiver:tiltak-refusjon-api"
    - name: API_URL
      value: http://tiltak-refusjon-api
    - name: SESSION_SECRET
      value: changeme
  accessPolicy:
    outbound:
      rules:
        - application: tiltak-refusjon-api
      external:
        - host: https://dekoratoren.dev.nav.no
