apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-arbeidsgiver
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - {{ingress}}
  liveness:
    path: /refusjon/isAlive
    initialDelay: 10
  readiness:
    path: /refusjon/isReady
    initialDelay: 10
  env:
    {{#each env}}
    - name: "{{@key}}"
      value: "{{{this}}}"
    {{/each}}
    - name: HOST
      value: {{ingress}}
  accessPolicy:
    outbound:
      rules:
        {{#each outbound}}
          - application: "{{this}}"
        {{/each}}
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
  {{#if labs}}
  replicas:
    min: 1
    max: 1
  {{/if}}
  {{#unless labs}}
  replicas:
    min: 1
    max: 2
  tokenx:
    enabled: true
  idporten:
    enabled: true
  envFrom:
    - secret: tiltak-refusjon-session-encrypt-key
    - secret: tiltak-refusjon-arbeidsgiver-redis
  {{/unless}}