ingress: https://tiltak-refusjon.nav.no
labs: false
host:
  - www.nav.no
outbound:
  - tiltak-refusjon-api
  - tiltak-refusjon-arbeidsgiver-redis
  - sentry.gc.nav.no
env:
  DECORATOR_URL: https://www.nav.no/dekoratoren
  API_AUDIENCE: "prod-gcp:arbeidsgiver:tiltak-refusjon-api"
  API_URL: http://tiltak-refusjon-api
  REDIS_HOST: tiltak-refusjon-arbeidsgiver-redis
slack_alert_channel: tiltak-alerts