export enum RefusjonStatus {
    KLAR_FOR_INNSENDING = 'KLAR_FOR_INNSENDING',
    GODKJENT_MINUSBELØP = 'GODKJENT_MINUSBELØP',
    FOR_TIDLIG = 'FOR_TIDLIG',
    SENDT_KRAV = 'SENDT_KRAV',
    UTBETALT = 'UTBETALT',
    UTBETALING_FEILET = 'UTBETALING_FEILET',
    UTGÅTT = 'UTGÅTT',
    ANNULLERT = 'ANNULLERT',
    KORRIGERT = 'KORRIGERT',
    GODKJENT_NULLBELØP = 'GODKJENT_NULLBELØP',
}

export enum KorreksjonStatus {
    UTKAST = 'UTKAST',
    TILLEGSUTBETALING = 'TILLEGSUTBETALING',
    TILLEGGSUTBETALING_UTBETALT = 'TILLEGGSUTBETALING_UTBETALT',
    TILLEGGSUTBETALING_FEILET = 'TILLEGGSUTBETALING_FEILET',
    OPPGJORT = 'OPPGJORT',
    TILBAKEKREVING = 'TILBAKEKREVING',
}
