#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
yarn run pretty-svg

echo "---------------------------------------------------"
echo "     HUSK Å OPPDATERE SAKSBEHANDLERLØSNINGEN!"     
echo "---------------------------------------------------"