name: Bygg og deploy storybook

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bygg:
    permissions:
      contents: read
      id-token: write
    name: Bygg og deploy
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Konfigurer Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm install
        run: npm ci
      - name: Bygg storybook
        run: npm run build-storybook
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: arbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy til dev-gcp
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev-gcp-storybook.yml
          VAR: image=${{ needs.bygg.outputs.image }}
