name: Bygg og deploy main

on:
  push:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  IMAGE: ghcr.io/${{ github.repository }}/tiltak-refusjon-arbeidsgiver:${{ github.sha }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  bygg:
    name: Bygg og deploy
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - name: Server yarn install
        working-directory: ./server
        run: yarn install
      - name: Server yarn build
        working-directory: ./server
        run: yarn build
      - name: Frontend yarn install
        run: yarn install
      - name: Frontend yarn build
        run: yarn build
      - name: Sett opp sentry release
        run: yarn run release
      - name: Bygg, tag og push Docker-image
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev:
    name: Deploy til dev-gcp
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          PRINT_PAYLOAD: true
          VARS: .nais/dev.yml

  deploy-labs:
    name: Deploy til dev-gcp (tidligere labs)
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          PRINT_PAYLOAD: true
          VARS: .nais/labs.yml

  deploy-prod:
    name: Deploy til prod-gcp
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yml
          PRINT_PAYLOAD: true
          VARS: .nais/prod.yml